services:
  - type: web
    name: idphoto-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    region: singapore
    autoDeploy: true